webtalk_init -webtalk_dir C:/Users/hugof/Documents/KU Leuven/FIIW/BAC3/Complex Digital Design/Lab2/lab2/lab2.sim/sim_1/behav/xsim/xsim.dir/uart_top_TB_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Mar 21 23:59:24 2025" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2902540" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "ac883497-b2b3-4c68-94df-486bfe5029e3" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "5a610ac22dc74dcfa3775e63f9061639" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "103" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 3 4300U with Radeon Graphics         " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2695 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "33.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "16583 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.01_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "8008_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1175669888 -regid "" -xml C:/Users/hugof/Documents/KU Leuven/FIIW/BAC3/Complex Digital Design/Lab2/lab2/lab2.sim/sim_1/behav/xsim/xsim.dir/uart_top_TB_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/hugof/Documents/KU Leuven/FIIW/BAC3/Complex Digital Design/Lab2/lab2/lab2.sim/sim_1/behav/xsim/xsim.dir/uart_top_TB_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/hugof/Documents/KU Leuven/FIIW/BAC3/Complex Digital Design/Lab2/lab2/lab2.sim/sim_1/behav/xsim/xsim.dir/uart_top_TB_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
